language: python

services:
  - docker

install:
  - docker build -t slackify .

script:
  - ./scripts/unit-test.sh

after_success:
  - if [$TRAVIS_BRANCH == "master"]; 
    ./scripts/gcr-push-via-vault.sh;
    fi