language: python

services:
  - docker

install:
  - docker build -t slackify .

script:
  - ./scripts/unit-test.sh

deploy:
  provider: script
  script: ./scripts/gcr-push-via-vault.sh
  on:
    branch: master